version: '3.8'

services:
  web:
    build: .
    container_name: task-manager
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - DATABASE_URL=sqlite:///tasks.db
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - SECRET_KEY=${SECRET_KEY}
    env_file:
      - .env
    volumes:
      - .:/app
      - sqlite_data:/app/instance

volumes:
  sqlite_data: